name: integration

on:
  workflow_run:
    workflows: ["module"]
    types: [completed]

jobs:
  nuxt:
    runs-on: ${{ matrix.os }}

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    permissions:
      contents: read
      pull-requests: read

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [22]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: benjamincanac/app-ui3

      - name: Set commit SHA from triggering workflow
        run: echo "COMMIT=${GITHUB_EVENT_WORKFLOW_RUN_HEAD_SHA:0:7}" >> $GITHUB_ENV

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install https://pkg.pr.new/@nuxt/ui@${{ env.COMMIT }}

      - name: Typecheck
        run: pnpm run typecheck

      - name: Build
        run: pnpm run build

  vue:
    runs-on: ${{ matrix.os }}

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    permissions:
      contents: read
      pull-requests: read

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [22]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: benjamincanac/app-ui3-vue

      - name: Set commit SHA from triggering workflow
        run: echo "COMMIT=${GITHUB_EVENT_WORKFLOW_RUN_HEAD_SHA:0:7}" >> $GITHUB_ENV

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install https://pkg.pr.new/@nuxt/ui@${{ env.COMMIT }}

      # - name: Typecheck
      #   run: pnpm run typecheck

      - name: Build
        run: pnpm run build